// menu
export const SET_URL_PARAMS_LINKS = "SET_URL_PARAMS_LINKS"
export const SET_ACCOUNT_WEB = "SET_ACCOUNT_WEB"
export const SET_ACCOUNT_MOBILE = "SET_ACCOUNT_MOBILE"
export const SET_DASHBOARD_MOBILE = "SET_DASHBOARD_MOBILE"
export const SET_SELECT_UTC = "SET_SELECT_UTC"
export const SET_MENU_THEME = "SET_MENU_THEME"
export const FIRST_LOAD = "FIRST_LOAD"
export const SET_CONNECT_GLOBAL = "SET_CONNECT_GLOBAL"



//user
export const SET_USER_DATA = "SET_USER_DATA"
export const SET_FORM_ENCHANGE = "SET_FORM_ENCHANGE"
export const SET_USER_USER_ID = "SET_USER_USER_ID"
export const SET_DEFAULT_CANCEL = "SET_DEFAULT_CANCEL"
export const SET_CONFIRM_CALENDAR = "SET_CONFIRM_CALENDAR"
export const SET_FORM_TRAIDING_AMOUNT = "SET_FORM_TRAIDING_AMOUNT"
export const SET_FORM_ACCOUNT_STATUS = "SET_FORM_ACCOUNT_STATUS"
export const SET_FORM_BOT_STATUS = "SET_FORM_BOT_STATUS"
export const SET_UPDATE_BALANCE = "SET_UPDATE_BALANCE"
export const SET_DEMO_BALANCE = "SET_DEMO_BALANCE"
export const UP_GRAPH_DATA = "UP_GRAPH_DATA"




// table
export const SET_TABLE_SORT = "SET_TABLE_SORT"
export const SET_TABLE_DATA = "SET_TABLE_DATA"
export const SET_TABLE_SESSION_RESULT = "SET_TABLE_SESSION_RESULT"

